[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

[lib]
name = "day_17_lib"
path = "src/lib.rs"

[[bin]]
name = "part_1"
path = "src/bin/part_1.rs"

[[bin]]
name = "part_2"
path = "src/bin/part_2.rs"

[dependencies]
library = { path = "../library" }
regex = "1.10.2"
